export enum SkillFilter {
  ALL = "all",
  FRONTEND = "frontend",
  BACKEND = "backend",
  DATABASE = "database",
  OTHER = "other",
}

export enum SkillName {
  BITRIX = "bitrix",
  BOOTSTRAP = "bootstrap",
  CONCOURSE = "concourse",
  CSS = "css",
  DOCKER = "docker",
  FIGMA = "figma",
  GIT = "git",
  GOOGLE = "google",
  HTML = "html",
  JEST = "jest",
  JIRA = "jira",
  JS = "js",
  LARAVEL = "laravel",
  LINUX = "linux",
  MONGODB = "mongodb",
  MYSQL = "mysql",
  NEXTJS = "nextjs",
  PHP = "php",
  POSTGRESQL = "postgresql",
  REACT = "react",
  REDIS = "redis",
  REDUX = "redux",
  TYPESCRIPT = "typescript",
  WEBPACK = "webpack",
}

export const skillsMapper: Record<SkillFilter, SkillName[]> = {
  [SkillFilter.ALL]: Object.values(SkillName),
  [SkillFilter.FRONTEND]: [
    SkillName.HTML,
    SkillName.CSS,
    SkillName.JS,
    SkillName.REACT,
    SkillName.NEXTJS,
    SkillName.TYPESCRIPT,
  ],
  [SkillFilter.BACKEND]: [SkillName.PHP, SkillName.LARAVEL],
  [SkillFilter.DATABASE]: [
    SkillName.MYSQL,
    SkillName.MONGODB,
    SkillName.POSTGRESQL,
  ],
  [SkillFilter.OTHER]: [
    SkillName.BOOTSTRAP,
    SkillName.CONCOURSE,
    SkillName.DOCKER,
    SkillName.FIGMA,
    SkillName.GIT,
    SkillName.GOOGLE,
    SkillName.JEST,
    SkillName.JIRA,
    SkillName.LINUX,
    SkillName.REDUX,
    SkillName.WEBPACK,
  ],
};
