name: Deploy on dev.vshevchuk.ru

on:
  push:
    branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Set key hosting
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"

      # Build
      - name: Build
        run: |
          npm ci
          npm run eslint
          npm run stylelint
          npm run build

      # Deploy
      - run: cd build && rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . u1582797@31.31.198.106:/var/www/u1582797/data/www/dev.vshevchuk.ru
